### ISSUE TITLE
 fzf-flatpak.sh doesn't work in bash

### ISSUE THREAD

**Issue by QiangF** [lime-desu/dootsfile#20]

**Comment by Ioulan** [comment]
Ah yes sorry for that, I didn't actually test the script on bash 😅. (Since I'm using zsh as my interactive shell).

For some reason, I'm having a problem using ALT binding on bash. So to fix the **ALT** key are changed into **CTRL** key (bash only)

   - `ALT-F` `ALT-I` for Install
   - `ALT-F` `ALT-U` for Uninstall
   - `ALT-F` `ALT-R` for Running Apps

// Still the same (hardcoded)
   - `ALT-?` Show bindings
